blogsite/blogsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (
    LoginView, 
    LogoutView, 
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('myblog.urls')),
    path('login/', LoginView.as_view(template_name='myblog/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='myblog/logout.html'), name='logout'),
    path('password-reset/', PasswordResetView.as_view(template_name='myblog/password_reset.html'), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='myblog/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>', PasswordResetConfirmView.as_view(template_name='myblog/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(template_name='myblog/password_reset_complete.html'), name='password_reset_complete'),
] 

# serve static files
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogsite/myblog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('register/', views.register, name='register'),
    path('signup/', views.signupPage, name='signup'),
    path('post-form/', views.CreatePostView.as_view(),name='create-post'),
    path('post/<int:pk>/', views.PostView.as_view(), name='post-view'),
    path('post/author/<str:username>/', views.AuthorPostsView.as_view(), name='author-posts-view'),
    path('post/<int:pk>/update', views.UpdatePostView.as_view(), name='update-post-view'),
    path('post/<int:pk>/delete', views.DeletePostView.as_view(), name='delete-post-view'),
] 

blogsite/myblog/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User
from django_summernote.fields import SummernoteTextField

class Post(models.Model):
    title = models.CharField(max_length=200)
    body = SummernoteTextField()
    image = models.ImageField(default='default.jpg', upload_to='blog_pics')
    date_published = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:home')

blogsite/myblog/forms.py
from django import forms
from .models import Post
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserSignupForm(UserCreationForm):
    
    first_name = forms.CharField(max_length=100) 
    last_name = forms.CharField(max_length=100)
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']

blogsite/myblog/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from .forms import UserSignupForm
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from .models import Post


# Class based views
'''
NOTE: 
Class based views look for templates with the format:
<app>/<model>_<viewtype>.html
'''

class HomePageView(ListView):
    template_name = 'myblog/index.html'
    context_object_name = 'post_list'
    paginate_by = 5

    def get_queryset(self):
        return Post.objects.filter(date_published__lte=timezone.now()).order_by('-date_published')[:10]


class PostView(DetailView):
    model = Post


class AuthorPostsView(ListView):
    context_object_name = 'post_list'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(date_published__lte=timezone.now(), author=user).order_by('-date_published')[:10]


class CreatePostView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'body', 'image']

    # template_name='myblog/post_form.html'
    # success_url can be used to redirect to a link after post is created

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class UpdatePostView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    template_name = 'myblog/post_form.html'
    fields = ['title', 'body', 'image']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    # UserPassesTestMixin runs this function
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class DeletePostView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    # UserPassesTestMixin runs this function
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


# Function based views

def register(request):

    if request.method == 'POST':
        signupForm = UserSignupForm(request.POST)

        if signupForm.is_valid():
            signupForm.save()
            messages.success(request, 'Account created!')
            return redirect(reverse('blog:home'))

        else:
            signupForm = UserSignupForm()
        return render(request, 'myblog/register.html', {'signupForm': signupForm})


def signupPage(request):
    signupForm = UserSignupForm()
    return render(request, 'myblog/register.html', {'signupForm': signupForm})

blogsite/myblog/templates/myblog/about.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Clean Blog - Start Bootstrap Theme</title>

  <!-- Bootstrap core CSS -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="css/clean-blog.min.css" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="index.html">Start Bootstrap</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="index.html">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="about.html">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="post.html">Sample Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="contact.html">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('img/about-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>About Me</h1>
            <span class="subheading">This is what I do.</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
      </div>
    </div>
  </div>

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2020</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'myblog/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'myblog/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'myblog/js/clean-blog.min.js' %}"></script>

</body>

</html>

blogsite/myblog/templates/myblog/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Siraluda Newsstand</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'myblog/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static 'myblog/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="{% static 'myblog/css/clean-blog.min.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="{% url 'blog:home' %}">Siraluda Newsstand</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:home' %}">Home</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:create-post' %}">New Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:signup' %}">Register</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  {% block content %}{% endblock %}
  
  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Siraluda 2020</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'myblog/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'myblog/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'myblog/js/clean-blog.min.js' %}"></script>

</body>

</html>

blogsite/myblog/templates/myblog/index.html
{% extends 'myblog/base.html' %}
{% block content %}

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('../../static/myblog/img/home.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Siraluda Newsstand</h1>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        {% if post_list %}
        {% for post_item in post_list %}
        <div class="post-preview">
          <a href="{% url 'blog:post-view' post_item.id %}">
            <h2 class="post-title">
              {{ post_item.title|safe }}
            </h2>
            <h3 class="post-subtitle">
              {{ post_item.body|truncatewords:30|safe }}
            </h3>
          </a>
          <p class="post-meta">Posted by
            <a href="{% url 'blog:author-posts-view' post_item.author.username %}">{{ post_item.author.first_name }}</a>
            on {{ post_item.date_published|date:'F d, Y'}}</p>
        </div>
        <hr>
        {% endfor %}
        {% endif %}

        <!-- Pager -->
        <div class="clearfix">

          {% if is_paginated %}
            <!-- {% if page_obj.has_previous %}
              <a class="btn btn-outline-info mb=4" href="?page=1">First</a>
              <a class="btn btn-outline-info mb=4" href="?page={{ page_obj.previous_page_number }}">&larr;</a>
            {% endif %} -->

            {% for num in page_obj.paginator.page_range %}
              
              {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
              {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
              {% endif %}

            {% endfor %}

            <!-- {% if page_obj.has_next %}
              {% if page_obj.has_previous %}
                <a class="btn btn-outline-info mb=4" href="?page={{ page_obj.next_page_number }}">&rarr;</a>
                <a class="btn btn-outline-info mb=4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
              {% endif %}
            {% endif %} -->

          {% endif %}
        </div>
      </div>
    </div>
  </div>

  {% endblock content %}

blogsite/myblog/templates/myblog/login.html
{% extends 'myblog/base.html' %}
{% block content %}
{% load crispy_forms_tags %}
  <!-- Page Header -->
  <header class="masthead" style="background-image: url('../../static/myblog/img/login.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>Login</h1>
            <span class="subheading">Have questions? I have answers.</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
          <!--Form-->
        <form name="sentMessage" id="contactForm" novalidate method="POST">
          <fieldset class="form-group">
          {% csrf_token %}
          {{form|crispy}}
          </fieldset>
          <br>
          <div id="success"></div>
          <button type="submit" class="btn btn-primary" id="sendMessageButton">Login</button>
          <small class="text-muted ml-2"><a href="{% url 'password_reset' %}">Forgot Password?</a></small>
        </form>
      </div>
    </div>
  </div>

{% endblock content %}
 

blogsite/myblog/templates/myblog/logout.html
{% extends 'myblog/base.html' %}
{% block content %}

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('../../static/myblog/img/logout.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>You just logged out</h1>
            <span class="subheading">Go back to the <a style="color:cadetblue;" href="{% url 'blog:home' %}">main page</a> or <a style="color:cadetblue;" href="{% url 'login' %}">login</a> again</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock content %}

blogsite/myblog/templates/myblog/password_reset.html
{% extends 'myblog/base.html' %}
{% block content %}
{% load crispy_forms_tags %}
  <!-- Page Header -->
  <header class="masthead" style="background-image: url('../../static/myblog/img/login.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>Reset Password</h1>
            <span class="subheading">Please enter your account email</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
          <!--Form-->
        <form name="sentMessage" id="contactForm" novalidate method="POST">
          <fieldset class="form-group">
          {% csrf_token %}
          {{form|crispy}}
          </fieldset>
          <br>
          <div id="success"></div>
          <button type="submit" class="btn btn-primary" id="sendMessageButton">Request Password Reset</button>
        </form>
      </div>
    </div>
  </div>

{% endblock content %}

blogsite/myblog/templates/myblog/password_reset_complete.html
{% extends 'myblog/base.html' %}
{% block content %}

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('../../static/myblog/img/logout.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>New password added!</h1>
            <span class="subheading">Go back to the <a style="color:cadetblue;" href="{% url 'blog:home' %}">main page</a> or <a style="color:cadetblue;" href="{% url 'login' %}">login</a> again</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock content %}

blogsite/myblog/templates/myblog/password_reset_done.html
{% extends 'myblog/base.html' %}
{% block content %}

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('../../static/myblog/img/logout.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>Reset Password</h1>
            <span class="subheading">An email has been sent with a link to reset your password</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock content %}

blogsite/myblog/templates/myblog/post_confirm_delete.html
{% extends 'myblog/base.html' %}
{% block content %}
{% load crispy_forms_tags %}
  <!-- Page Header -->
  <header class="masthead" style="background-image: url('../../static/myblog/img/login.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>Delete Post?</h1>
            <span class="subheading">Have questions? I have answers.</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
          <!--Form-->
        <form name="sentMessage" id="contactForm" novalidate method="POST">
          <fieldset class="form-group">
          {% csrf_token %}
          <h2>Are you sure you want to delete post "{{object.title}}"</h2>
          </fieldset>
          <br>
          <div id="success"></div>
          <button type="submit" class="btn btn-outline-danger" id="sendMessageButton">Yes, Delete</button>
          <a href="{% url 'blog:post-view' object.id %}" class="btn btn-outline-secondary" id="sendMessageButton">Cancel</a>
        </form>
      </div>
    </div>
  </div>

{% endblock content %}

blogsite/myblog/templates/myblog/post_detail.html
{% extends 'myblog/base.html' %}
{% block content %}
  <!-- Page Header -->
  <header class="masthead" style="background-image: url('{{object.image.url}}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="post-heading">
            <h1>{{object.title|safe}}</h1>
            <h2 class="subheading">{{object.body|truncatewords:10|safe}}</h2>
            <span class="meta">Posted by
              <a href="{% url 'blog:author-posts-view' object.author.username %}">{{object.author.first_name}}</a>
              on {{object.date_published|date:'F d, Y'}}</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Post Content -->
  <article>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <p>{{object.body|safe}}</p>
        </div>
        <div>
          {% if object.author == user %}
          <a href="{% url 'blog:update-post-view' object.id %}" class="btn btn-outline-secondary btn-sm mt-1 mb-1" id="sendMessageButton">Update</a>
          <a href="{% url 'blog:delete-post-view' object.id %}" class="btn btn-outline-danger btn-sm mt-1 mb-1" id="sendMessageButton">Delete</a>
          {%endif%}
        </div>
      </div>
    </div>
  </article>
  
{% endblock content %}

 

blogsite/myblog/templates/myblog/post_list.html
{% extends 'myblog/base.html' %}
{% block content %}

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('../../static/myblog/img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Siraluda Newsstand</h1>
            <span class="subheading"></span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        {% if post_list %}
        {% for post_item in post_list %}
        <div class="post-preview">
          <a href="{% url 'blog:post-view' post_item.id %}">
            <h2 class="post-title">
              {{ post_item.title|safe }}
            </h2>
            <h3 class="post-subtitle">
              {{ post_item.body|truncatewords:30|safe }}
            </h3>
          </a>
          <p class="post-meta">Posted by
            <a href="#">{{ post_item.author.first_name }}</a>
            on {{ post_item.date_published|date:'F d, Y'}}</p>
        </div>
        <hr>
        {% endfor %}
        {% endif %}

        <!-- Pager -->
        <div class="clearfix">

          {% if is_paginated %}
            <!-- {% if page_obj.has_previous %}
              <a class="btn btn-outline-info mb=4" href="?page=1">First</a>
              <a class="btn btn-outline-info mb=4" href="?page={{ page_obj.previous_page_number }}">&larr;</a>
            {% endif %} -->

            {% for num in page_obj.paginator.page_range %}
              
              {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
              {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
              {% endif %}

            {% endfor %}

            <!-- {% if page_obj.has_next %}
              {% if page_obj.has_previous %}
                <a class="btn btn-outline-info mb=4" href="?page={{ page_obj.next_page_number }}">&rarr;</a>
                <a class="btn btn-outline-info mb=4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
              {% endif %}
            {% endif %} -->

          {% endif %}
        </div>
      </div>
    </div>
  </div>

  {% endblock content %}

blogsite/myblog/templates/myblog/register.html
{% extends 'myblog/base.html' %}
{% block content %}
{% load crispy_forms_tags %}

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('../../static/myblog/img/register.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>Register</h1>
            <span class="subheading">Have questions? I have answers.</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
        <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
        <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
        <!-- To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
        <form name="sentMessage" id="contactForm" action="{% url 'blog:register' %}" method="POST" novalidate>
          {% csrf_token %}
          <fieldset class="form-group">
            {{ signupForm|crispy }}
          </fieldset>
          <br>
          <div id="success"></div>
          <button type="submit" class="btn btn-primary" id="sendMessageButton">Register</button>
        </form>
      </div>
    </div>
  </div>

{% endblock content %}